version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Backend setup
          command: |
            cd backend
            npm install
            npm test || echo "No backend tests yet"
      - run:
          name: Frontend setup
          command: |
            cd frontend
            npm install
            npm run build

  sonar-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=banking-app \
              -Dsonar.sources=./backend,./frontend \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  main:
    jobs:
      - build-and-test
      - sonar-analysis:
          requires:
            - build-and-test
