version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  # ================================
  # Job de Build & Test
  # ================================
  build-and-test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout

      # Backend setup
      - run:
          name: Backend setup
          command: |
            cd backend
            npm install
            # Opcional: rodar testes com cobertura
            # npm test -- --coverage

      # Frontend setup
      - run:
          name: Frontend setup
          command: |
            cd frontend
            npm ci
            chmod +x node_modules/.bin/* || true
            npm run build
            # Opcional: rodar testes com cobertura
            # npm test -- --coverage

  # ================================
  # Job de Análise SonarQube
  # ================================
  sonar-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

  # ================================
  # Job de Análise de Segurança (ScoutSuite)
  # ================================
  scout-analysis:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Instalar ScoutSuite
          command: |
            pip install scoutsuite boto3
      - run:
          name: Rodar ScoutSuite
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
            scout aws --profile default || true
      - store_artifacts:
          path: scoutsuite-report
          destination: scoutsuite-report

# ================================
# Workflow Principal
# ================================
workflows:
  main:
    jobs:
      - build-and-test
      - sonar-analysis:
          requires:
            - build-and-test
      - scout-analysis:
          requires:
            - build-and-test
